import { StyleSheet, Dimensions } from 'react-native';
import { StatusBar } from 'expo-status-bar';

const {width, height} = Dimensions.get('window');

const metrics = {
  screenWidth: width < height ? width : height,
  screenHeight: width < height ? height : width,
};

const size = {
  s: metrics.screenWidth * (8 / 365),
  xs: metrics.screenWidth * (10 / 365),
  sm: metrics.screenWidth * (12 / 365),
  md: metrics.screenWidth * (14 / 365),
  lg: metrics.screenWidth * (16 / 365),
  xl: metrics.screenWidth * (18 / 365),
};

const weight = {
  bold: '700',
  semibold: '400',
  light: '300',
};

const type = {
  regular: 'Poppins-SemiBold',
  bold: 'Poppins-Bold',
  semibold: 'Poppins-Regular',
};

export const color = {
  primary: '#E5B323',
  secondary: '#263238',
  info: '#0dcaf0',
  success: '#198754',
  warning: '#ffc107',
  danger: '#dc3545',
  light: '#f8f9fa',
  dark: '#212529',
  white: '#FFFFFF',
  black: '#000000',
  gray: '#D9D9D9',
};

const styles = StyleSheet.create({
  center: {
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
  },
  start: {
    alignItems: 'flex-start',
    alignContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  end: {
    alignItems: 'flex-end',
    alignContent: 'flex-end',
    alignSelf: 'flex-end',
  },
  space_between: {
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  row: {
    flexDirection: 'row',
    marginVertical: 30,
  },
  app: {
    flex: 1,
    backgroundColor: color.white,
    paddingTop: StatusBar.currentHeight,
  },
  container: {
    flex: 1,
    backgroundColor: color.white,
    paddingHorizontal: 30,
  },
  logo: {
    maxWidth: 200,
  },
  page: {
    flex: 1,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
  },
  header: {
    backgroundColor: color.white,
    alignItems: 'center',
    flexDirection: 'row',
    alignSelf: 'stretch',
    justifyContent: 'space-between',
    paddingTop: 5,
  },
  header_rounded: {
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    paddingTop: 30,
    paddingHorizontal: 40,
  },
  footer: {
    height: 70,
    backgroundColor: color.secondary,
    alignItems: 'center',
    flexDirection: 'row',
    alignSelf: 'stretch',
    justifyContent: 'space-around',
    padding: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  bars: {
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    marginVertical: 30,
  },
  bar: {
    flex: 1,
    maxWidth: 50,
    justifyContent: 'center',
    backgroundColor: color.primary,
    paddingHorizontal: 3,
    paddingVertical: 5,
    marginHorizontal: 5,
    borderRadius: 15,
  },
  illustration: {
    width: '100%',
    height: '70%',
  },
  modalBody: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#475156cc',
  },
  modalView: {
    margin: 20,
    backgroundColor: color.secondary,
    borderRadius: 8,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '90%',
  },
  modalBottomBody: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    backgroundColor: '#475156cc',
  },
  modalBottomView: {
    backgroundColor: color.secondary,
    padding: 20,
    paddingTop: 15,
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    elevation: 5,
    width: '100%',
  },
  modalBottomSliderIndicatorRow: {
    flexDirection: 'row',
    marginBottom: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBottomSliderIndicator: {
    backgroundColor: color.primary,
    borderRadius: 30,
    height: 4,
    width: 45,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: '45%',
  },
  activity: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fw_normal: {
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
  },
  fw_bold: {
    fontWeight: weight.semibold,
    fontFamily: type.bold,
  },
  fw_bolder: {
    fontWeight: weight.semibold,
    fontFamily: type.bold,
  },
  text_s: {
    color: color.black,
    fontSize: size.s,
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
  },
  text_xs: {
    color: color.black,
    fontSize: size.xs,
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
  },
  text_sm: {
    color: color.black,
    fontSize: size.sm,
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
  },
  text_md: {
    color: color.black,
    fontSize: size.md,
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
  },
  text_lg: {
    color: color.black,
    fontSize: size.lg,
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
  },
  text_xl: {
    color: color.black,
    fontSize: size.xl,
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
  },
  form: {
    backgroundColor: '#fff',
  },
  field: {
    marginBottom: 30,
  },
  input: {
    padding: 15,
    borderRadius: 10,
    borderColor: color.primary,
    borderWidth: 2,
  },
  password_icon: {
    position: 'absolute',
    marginTop: 40,
    marginLeft: '90%',
  },
  date_icon: {
    position: 'absolute',
    marginTop: 15,
    marginLeft: '90%',
  },
  button_stretch: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    alignSelf: 'stretch',
  },
  button_sm: {
    fontSize: size.sm,
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
    padding: 10,
    borderRadius: 5,
  },
  button_md: {
    fontSize: size.md,
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
    padding: 15,
    borderRadius: 10,
  },
  button_lg: {
    fontSize: size.lg,
    fontWeight: weight.semibold,
    fontFamily: type.semibold,
    padding: 30,
    borderRadius: 15,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 100,
    backgroundColor: color.primary,
  },
  text_color_primary: { color: '#E5B323' },
  text_color_secondary: { color: '#263238' },
  text_color_info: { color: '#0dcaf0' },
  text_color_success: { color: '#198754' },
  text_color_warning: { color: '#ffc107' },
  text_color_danger: { color: '#dc3545' },
  text_color_light: { color: '#f8f9fa' },
  text_color_dark: { color: '#212529' },
  text_color_white: { color: '#FFFFFF' },
  text_color_black: { color: '#000000' },
  text_color_gray: { color: '#D9D9D9' },
  bg_color_primary: { backgroundColor: '#E5B323' },
  bg_color_secondary: { backgroundColor: '#263238' },
  bg_color_info: { backgroundColor: '#0dcaf0' },
  bg_color_success: { backgroundColor: '#198754' },
  bg_color_warning: { backgroundColor: '#ffc107' },
  bg_color_danger: { backgroundColor: '#dc3545' },
  bg_color_light: { backgroundColor: '#f8f9fa' },
  bg_color_dark: { backgroundColor: '#212529' },
  bg_color_white: { backgroundColor: '#FFFFFF' },
  bg_color_black: { backgroundColor: '#000000' },
  bg_color_gray: { backgroundColor: '#D9D9D9' },
  radius_s: { borderRadius: 1 },
  radius_xs: { borderRadius: 3 },
  radius_sm: { borderRadius: 5 },
  radius_md: { borderRadius: 10 },
  radius_lg: { borderRadius: 15 },
  radius_xl: { borderRadius: 20 },
  border_width_s: { borderWidth: 1 },
  border_width_xs: { borderWidth: 3 },
  border_width_sm: { borderWidth: 5 },
  border_width_md: { borderWidth: 10 },
  border_width_lg: { borderWidth: 15 },
  border_width_xl: { borderWidth: 20 },
  border_color_primary: { borderColor: '#E5B323' },
  border_color_secondary: { borderColor: '#263238' },
  border_color_info: { borderColor: '#0dcaf0' },
  border_color_success: { borderColor: '#198754' },
  border_color_warning: { borderColor: '#ffc107' },
  border_color_danger: { borderColor: '#dc3545' },
  border_color_light: { borderColor: '#f8f9fa' },
  border_color_dark: { borderColor: '#212529' },
  border_color_white: { borderColor: '#FFFFFF' },
  border_color_black: { borderColor: '#000000' },
  border_color_gray: { borderColor: '#D9D9D9' },
  padding_s: {
    padding: 1,
    s: { paddingStart: 1 },
    e: { paddingEnd: 1 },
    t: { paddingTop: 1 },
    b: { paddingBottom: 1 },
    xy: { padding: 1 },
    x: { paddingHorizontal: 1 },
    y: { paddingVertical: 1 }
  },
  padding_xs: {
    padding: 5,
    s: { paddingStart: 5 },
    e: { paddingEnd: 5 },
    t: { paddingTop: 5 },
    b: { paddingBottom: 5 },
    xy: { padding: 5 },
    x: { paddingHorizontal: 5 },
    y: { paddingVertical: 5 }
  },
  padding_sm: {
    padding: 10,
    s: { paddingStart: 10 },
    e: { paddingEnd: 10 },
    t: { paddingTop: 10 },
    b: { paddingBottom: 10 },
    xy: { padding: 10 },
    x: { paddingHorizontal: 10 },
    y: { paddingVertical: 10 }
  },
  padding_md: {
    padding: 15,
    s: { paddingStart: 15 },
    e: { paddingEnd: 15 },
    t: { paddingTop: 15 },
    b: { paddingBottom: 15 },
    xy: { padding: 15 },
    x: { paddingHorizontal: 15 },
    y: { paddingVertical: 15 }
  },
  padding_lg: {
    padding: 30,
    s: { paddingStart: 30 },
    e: { paddingEnd: 30 },
    t: { paddingTop: 30 },
    b: { paddingBottom: 30 },
    xy: { padding: 30 },
    x: { paddingHorizontal: 30 },
    y: { paddingVertical: 30 }
  },
  padding_xl: {
    padding: 40,
    s: { paddingStart: 40 },
    e: { paddingEnd: 40 },
    t: { paddingTop: 40 },
    b: { paddingBottom: 40 },
    xy: { padding: 40 },
    x: { paddingHorizontal: 40 },
    y: { paddingVertical: 40 }
  },
  padding_xx: {
    padding: 50,
    s: { paddingStart: 50 },
    e: { paddingEnd: 50 },
    t: { paddingTop: 50 },
    b: { paddingBottom: 50 },
    xy: { padding: 50 },
    x: { paddingHorizontal: 50 },
    y: { paddingVertical: 50 }
  },
  margin_s: {
    margin: 1,
    s: { marginStart: 1 },
    e: { marginEnd: 1 },
    t: { marginTop: 1 },
    b: { marginBottom: 1 },
    xy: { margin: 1 },
    x: { marginHorizontal: 1 },
    y: { marginVertical: 1 }
  },
  margin_xs: {
    margin: 5,
    s: { marginStart: 5 },
    e: { marginEnd: 5 },
    t: { marginTop: 5 },
    b: { marginBottom: 5 },
    xy: { margin: 5 },
    x: { marginHorizontal: 5 },
    y: { marginVertical: 5 }
  },
  margin_sm: {
    margin: 10,
    s: { marginStart: 10 },
    e: { marginEnd: 10 },
    t: { marginTop: 10 },
    b: { marginBottom: 10 },
    xy: { margin: 10 },
    x: { marginHorizontal: 10 },
    y: { marginVertical: 10 }
  },
  margin_md: {
    margin: 15,
    s: { marginStart: 15 },
    e: { marginEnd: 15 },
    t: { marginTop: 15 },
    b: { marginBottom: 15 },
    xy: { margin: 15 },
    x: { marginHorizontal: 15 },
    y: { marginVertical: 15 }
  },
  margin_lg: {
    margin: 30,
    s: { marginStart: 30 },
    e: { marginEnd: 30 },
    t: { marginTop: 30 },
    b: { marginBottom: 30 },
    xy: { margin: 30 },
    x: { marginHorizontal: 30 },
    y: { marginVertical: 30 }
  },
  margin_xl: {
    margin: 40,
    s: { marginStart: 40 },
    e: { marginEnd: 40 },
    t: { marginTop: 40 },
    b: { marginBottom: 40 },
    xy: { margin: 40 },
    x: { marginHorizontal: 40 },
    y: { marginVertical: 40 }
  },
  margin_xx: {
    margin: 50,
    s: { marginStart: 50 },
    e: { marginEnd: 50 },
    t: { marginTop: 50 },
    b: { marginBottom: 50 },
    xy: { margin: 50 },
    x: { marginHorizontal: 50 },
    y: { marginVertical: 50 }
  }
});

export default styles;
